COMPILER = g++

RMDIR = rm -rdf

RM = rm -f

DEP_FLAGS = -M -MT $@ -MT $(BIN_PATH)/$(*F).o -MP -MF $@

LIBS = -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lm

INC_PATHS = -I $(INC_PATH) $(addprefix -I ,$(SDL_INC_PATH))

FLAGS = -std=c++11 -Wall -pedantic -Wextra -Wno-unused-parameter -Werror=init-self
DFLAGS = -ggdb -O0 -DDEBUG
RFLAGS = -O3 -mtune=native

INC_PATH = header
SRC_PATH = src
BIN_PATH = bin
DEP_PATH = dep

CPP_FILES = $(wildcard main/*.cpp) $(wildcard $(SRC_PATH)/engine/*.cpp)
INC_FILES = $(wildcard $(INC_PATH)/application/*.h) $(wildcard $(INC_PATH)/engine*.h)
FILE_NAMES = $(sort $(notdir $(CPP_FILES:.cpp=)) $(notdir $(INC_FILES:.h=)))
DEP_FILES = $(addprefix $(DEP_PATH)/,$(addsuffix .d,$(FILE_NAMES)))
OBJ_FILES = $(addprefix $(BIN_PATH)/,$(notdir $(CPP_FILES:.cpp=.o)))

EXEC = GameBuild

ifeq ($(OS),Windows_NT)
RMDIR = rd /s /q
RM = del /q

SDL_PATHS = C:/SDL2 C:/SDL2/x86_64-w64-mingw32

SDL_INC_PATH += $(addsuffix /include,$(SDL_PATHS))
LINK_PATH = $(addprefix -L,$(addsuffix /lib, $(SDL_PATHS)))
RFLAGS += -Wl,-subsystem,windows # Will not open a console window
LIBS := -lmingw32 -lSDL2main $(LIBS) 

EXEC := $(EXEC).exe

else

UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S), Darwin)
LIBS = -lm -framework SDL2 -framework SDL2_image -framework SDL2_mixer -framework SDL2_ttf

endif
endif

.PRECIOUS: $(DEP_FILES)
.PHONY: release debug clean folders help

all: debug

$(EXEC): $(OBJ_FILES)
	$(COMPILER) -o $@ $^ $(LINK_PATH) $(LIBS) $(FLAGS)

# Application
$(BIN_PATH)/%.o: $(DEP_PATH)/application/%.d | folders
	$(COMPILER) $(INC_PATHS) $(addprefix main/,$(notdir $(<:.d=.cpp))) -c $(FLAGS) -o $@

$(DEP_PATH)/application/%.d: main/%.cpp | folders
	$(COMPILER) $(INC_PATHS) $< $(DEP_FLAGS) $(FLAGS)

# Engine
$(BIN_PATH)/%.o: $(DEP_PATH)/engine/%.d | folders
	$(COMPILER) $(INC_PATHS) $(addprefix $(SRC_PATH)/engine/,$(notdir $(<:.d=.cpp))) -c $(FLAGS) -o $@

$(DEP_PATH)/engine/%.d: $(SRC_PATH)/engine/%.cpp | folders
	$(COMPILER) $(INC_PATHS) $< $(DEP_FLAGS) $(FLAGS)

clean:
	-$(RMDIR) $(DEP_PATH)
	-$(RMDIR) $(BIN_PATH)
	-$(RM) $(EXEC)


.SECONDEXPANSION:
-include $$(DEP_FILES)

release: FLAGS += $(RFLAGS)
release: $(EXEC)

debug: FLAGS += $(DFLAGS)
debug: $(EXEC)

folders:
ifeq ($(OS), Windows_NT)
	@if NOT exist $(DEP_PATH) (mkdir $(DEP_PATH) )
	@if NOT exist $(DEP_PATH)\application (mkdir $(DEP_PATH)\application )
	@if NOT exist $(DEP_PATH)\engine (mkdir $(DEP_PATH)\engine )
	@if NOT exist $(BIN_PATH) (mkdir $(BIN_PATH) )
	@if NOT exist $(INC_PATH) (mkdir $(INC_PATH) )
	@if NOT exist $(SRC_PATH) (mkdir $(SRC_PATH) )
else
	@mkdir -p $(DEP_PATH) $(DEP_PATH)/application $(DEP_PATH)/engine $(BIN_PATH) $(INC_PATH) $(SRC_PATH)
endif

print-% : ; @echo $* = $($*)

help:
ifeq ($(OS), Windows_NT)
	@echo.
endif
	@echo Available targets:
	@echo - release: Builds the release version
	@echo - debug: Builds the debug version
	@echo - clean: Cleans generated files
	@echo - folders: Generates project directories
	@echo - help: Show this help
ifeq ($(OS), Windows_NT)
	@echo.
endif